import { get, post } from '@/utils/request'
export const getUserList = (params) => get('/user/list', params)
export const getUserById = (uid) => get(`/user/selectById/${uid}`)
export const getAllUsers = () => get('/user/selectAllUsers')
export const addUser = (data) => post('/user/add', data)
export const transferUser = (data) => post('/user/deptTransfer', data)
export const updateUser = (data) => post('/user/updateInfo', data)
export const deleteUser = (data) => post('/user/delete', data)
export const updateUserStatus = (data) => post('/user/updateStatus', data)
export const updatePassword = (data) => post('/user/updatePassword', data)
export const exportUsers = (params) => get('/user/exportData', params)
export const sendUserEmailCode = (data) => post('/user/send-email-code', data)
export const changeEmail = (data) => post('/user/changeEmail', data)
export const sendPhoneCode = (data) => post('/api/send-phone-code', data)
export const changePhone = (data) => post('/api/change-phone', data)
